# Generated by Django 4.1.8 on 2023-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('colab_id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('secao', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('funcao', models.CharField(max_length=255)),
                ('reuniao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Jovem',
            fields=[
                ('jovem_id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('secao', models.CharField(max_length=100)),
                ('promessa', models.BooleanField(null=True)),
                ('data_nascimento', models.DateField()),
                ('valor_mensalidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('secao_id', models.AutoField(primary_key=True, serialize=False)),
                ('secao_nome', models.CharField(max_length=100)),
                ('secao_chefe', models.CharField(max_length=100)),
            ],
        ),
    ]
