# Generated by Django 4.1.8 on 2023-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('secao_id', models.AutoField(primary_key=True, serialize=False)),
                ('secao_nome', models.CharField(max_length=100)),
            ],
        ),
    ]
